import type { Metadata } from 'next'
import '../globals.css'
import { Fjalla_One, Roboto } from 'next/font/google'
import type React from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const fjalla = Fjalla_One({ subsets: ['latin'], weight: '400', variable: '--font-fjalla' })
const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={`${fjalla.variable} ${roboto.variable}`}>
      <body>{children}</body>
    </html>
  )
}
